# Generated by Django 3.2.25 on 2024-07-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
